SENSITIVE_TOPICS = [
    "suicide",
    "suicidal",
    "depression",
    "depressed",
    "self-harm",
    "kill myself",
    "want to die",
    "end my life",
    "can't go on",
    "hopeless",
    "hurting myself",
    "i want to disappear",
    "cutting",
    "i don’t want to live",
    "feeling empty",
    "overdose",
    "take my life",
    "i hate being alive",
    "i need to hurt myself",
    "i can’t take it anymore",
    "life is meaningless",
    "nothing matters",
    "rape",
    "sexual assault",
    "molestation",
    "abuse",
    "being abused",
    "ending it all",
    "jump off a bridge",
    "drown myself",
    "hang myself",
    "slit my wrists",
    "jump off a bridge",
    "drown myself",
    "hang myself",
    "slit my wrists",
    "unalive myself",
    "kys",
    "kms",
    "s/h",
    "s-h",
    "sh",
    "burn myself",
    "bleach",
    "i wish i was dead"
]